# This workflow will check the name of the branch to see if it meets project standards
name: branch-appropriate-to-merge

on:
  pull_request: # the workflow will trigger on every pull request event

jobs:
  is-this-branch-appropriate-to-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch names
        uses: tj-actions/branch-names@v2
        id: branch-name
      - name: Get Ref brach name
        run: |
          echo "${{ steps.branch-name.outputs.ref_branch }}"
      - name: Get Head Ref branch name
        if: github.event_name == 'pull_request'
        run: |
          echo "source branch: ${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "target branch: ${{ steps.branch-name.outputs.base_ref_branch }}"
