# This workflow will check the name of the branch to see if it meets project standards
name: check-source-branch-name

on:
  pull_request:
    branches-ignore:
      - main
      - master
        
jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - uses: kylepoland-dcss/action-branch-name@master
        with:
          regex: '(F|US|DE)\d+_.*' # match Fnnn_something, USnnn_something, and DEnnn_something
          allowed_prefixes: # All branches should start with the given prefix
          ignore: main,master # Ignore exactly matching branch names from convention
          min_length: # Min length of the branch name
          max_length: # Max length of the branch name
